import { KeyedMutator } from 'swr'
import { AxiosResponse } from 'axios'

export type WooProductType = {
    attributes: unknown[],
    average_rating: string,
    backordered: boolean,
    backorders: string,
    backorders_allowed: boolean,
    button_text: string,
    catalog_visibility: string,
    categories: {
        id: number,
        name: string,
        slug: string,
    },
    cross_sell_ids: unknown[],
    date_created: string,
    date_created_gmt: string,
    date_modified: string,
    date_modified_gmt: string,
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    default_attributes: unknown[],
    description: string,
    dimensions: {
        height:string,
        length: string,
        width: string,
    }
    download_expiry: number,
    download_limit: number,
    downloadable: boolean,
    downloads: unknown[],
    external_url: string,
    featured: boolean,
    grouped_products: unknown[],
    id: number,
    images: {
        alt: string,
        date_created: string,
        date_created_gmt: string,
        date_modified: string,
        date_modified_gmt: string,
        id: number,
        name: string,
        src: string,
    },
    low_stock_amount: null,
    manage_stock: boolean,
    menu_order: number,
    meta_data: unknown[],
name: string,
on_sale: boolean,
parent_id: number,
permalink: string,
price: string,
price_html: string,
purchasable: boolean,
purchase_note: string,
rating_count: number,
regular_price: string,
related_ids: unknown[],
reviews_allowed: boolean,
sale_price: string,
shipping_class: string,
shipping_class_id: number,
shipping_required: boolean,
shipping_taxable: boolean,
short_description: string,
sku: string,
slug: string,
sold_individually: boolean,
status: string,
stock_quantity: number,
stock_status: string,
tags: unknown[],
tax_class: string,
tax_status: string,
total_sales: number,
type: string,
upsell_ids: unknown[],
variations: unknown[],
virtual: boolean,
weight: string,
yoast_head: string,
yoast_head_json: {
    article_modified_time: string,
    article_publisher: string,
    canonical: string,
    description: string,
    og_description: string,
    og_image: unknown[],
    og_locale: string,
    og_site_name: string,
    og_title: string,
    og_type: string,
    og_url: string,
    robots: {
        index: string,
        follow: string,
        'max-snippet': string,
        'max-image-preview': string,
        'max-video-preview': string,
    },
    schema: {
        '@context': string,
        '@graph': unknown[],
    },
    title: string,
    twitter_card: string,
},
_links: {
        collection: {
            href: string,
        },
        self: {
            href: string,
        },
    }
}

export interface ProductContextProps {
    products: WooProductType[] | AxiosResponse,
    productNames: string[] | undefined,
    productMutate: KeyedMutator<AxiosResponse>,
}
